package com.example.myapp;

import com.codename1.rad.controllers.ApplicationController;
import com.codename1.rad.controllers.ControllerEvent;
import com.example.myapp.provider.MgrGroupsProvider;

import static com.codename1.rad.util.NonNull.with;
import com.example.myapp.views.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Test extends ApplicationController {

    public void onStartController(){
        addLookup(new MgrGroupsProvider());
    }

    public void actionPerformed(ControllerEvent evt) {
        with(evt, StartEvent.class, startEvent -> {
            if (!startEvent.isShowingForm()) {
                startEvent.setShowingForm(true);
                new StartPageController(this).show();
            }
        });
        super.actionPerformed(evt);
    }
}
